### YamlMime:ManagedReference
items:
- uid: Lucid.Branding.Text.TextStyleSettings
  commentId: T:Lucid.Branding.Text.TextStyleSettings
  id: TextStyleSettings
  parent: Lucid.Branding.Text
  children:
  - Lucid.Branding.Text.TextStyleSettings.textStyles
  langs:
  - csharp
  - vb
  name: TextStyleSettings
  nameWithType: TextStyleSettings
  fullName: Lucid.Branding.Text.TextStyleSettings
  type: Class
  source:
    id: TextStyleSettings
    path: ''
    startLine: 9441
  assemblies:
  - cs.temp.dll
  namespace: Lucid.Branding.Text
  syntax:
    content: 'public class TextStyleSettings : SingletonScriptableObject<TextStyleSettings>'
    content.vb: >-
      Public Class TextStyleSettings
          Inherits SingletonScriptableObject(Of TextStyleSettings)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Lucid.Branding.Text.TextStyleSettings.textStyles
  commentId: P:Lucid.Branding.Text.TextStyleSettings.textStyles
  id: textStyles
  parent: Lucid.Branding.Text.TextStyleSettings
  langs:
  - csharp
  - vb
  name: textStyles
  nameWithType: TextStyleSettings.textStyles
  fullName: Lucid.Branding.Text.TextStyleSettings.textStyles
  type: Property
  source:
    id: textStyles
    path: ''
    startLine: 9447
  assemblies:
  - cs.temp.dll
  namespace: Lucid.Branding.Text
  syntax:
    content: public List<TextStyle> textStyles { get; }
    parameters: []
    return:
      type: Global.List{Lucid.Branding.Text.TextStyle}
    content.vb: Public ReadOnly Property textStyles As List(Of TextStyle)
  overload: Lucid.Branding.Text.TextStyleSettings.textStyles*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Lucid.Branding.Text
  commentId: N:Lucid.Branding.Text
  name: Lucid.Branding.Text
  nameWithType: Lucid.Branding.Text
  fullName: Lucid.Branding.Text
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Lucid.Branding.Text.TextStyleSettings.textStyles*
  commentId: Overload:Lucid.Branding.Text.TextStyleSettings.textStyles
  name: textStyles
  nameWithType: TextStyleSettings.textStyles
  fullName: Lucid.Branding.Text.TextStyleSettings.textStyles
- uid: Global.List{Lucid.Branding.Text.TextStyle}
  commentId: '!:Global.List{Lucid.Branding.Text.TextStyle}'
  definition: Global.List`1
  name: List<TextStyle>
  nameWithType: List<TextStyle>
  fullName: List<Lucid.Branding.Text.TextStyle>
  nameWithType.vb: List(Of TextStyle)
  fullName.vb: List(Of Lucid.Branding.Text.TextStyle)
  name.vb: List(Of TextStyle)
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Lucid.Branding.Text.TextStyle
    name: TextStyle
    nameWithType: TextStyle
    fullName: Lucid.Branding.Text.TextStyle
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Lucid.Branding.Text.TextStyle
    name: TextStyle
    nameWithType: TextStyle
    fullName: Lucid.Branding.Text.TextStyle
  - name: )
    nameWithType: )
    fullName: )
- uid: Global.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: List<>
  nameWithType.vb: List(Of )
  fullName.vb: List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
